# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# forcing nvidia
env = LIBVA_DRIVER_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS=1

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.local/share/omarchy/default/hypr/apps/davinci-resolve.conf
source = ~/.local/state/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf


# Worspace configs 
workspace = 1, monitor:HDMI-A-2, default:true
workspace = 2, monitor:HDMI-A-2, default:false
workspace = 3, monitor:HDMI-A-2, default:false
workspace = 4, monitor:HDMI-A-2, default:false
workspace = 5, monitor:HDMI-A-2, default:false
workspace = 6, monitor:DP-6, default:true


# Toggle config flags dynamically
source = ~/.local/state/omarchy/toggles/hypr/*.conf
