-- Generated by scripts/hypr2lua.
-- Source: omarchy-hinterlands-theme/hyprland.conf

local activeBorderColor = "rgb(111111)"
local inactiveBorderColor = "rgba(555555ee)"

hl.config({
  general = {
    col = {
      active_border = activeBorderColor,
      inactive_border = inactiveBorderColor,
    },
    gaps_in = 8,
    gaps_out = 16,
  },
  group = {
    col = {
      border_active = activeBorderColor,
      border_inactive = inactiveBorderColor,
    },
  },
  decoration = {
    rounding = 0,
    rounding_power = 2,
    blur = {
      enabled = true,
      size = 4,
      passes = 3,
    },
    shadow = {
      enabled = true,
      range = 24,
      render_power = 8,
      color = "rgba(000000ff)",
      color_inactive = "rgba(dfdfdfff)",
    },
  },
})
